### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nmilosev** [eduardgorbunov/accelerated_clipping#1]
Dear colleagues,

We are writing to you regarding your paper "Stochastic optimization with heavy-tailed noise via accelerated gradient clipping" (arXiv:2005.10785) that we find very interesting and relevant to our research. We actually benchmark our research with respect to the methods you develop in the paper.

For our own work, we would also like to make the code available under an open source license. For the preparation of our open source code, we would like to use the code that you developed and posted publicly on Github: https://github.com/eduardgorbunov/accelerated_clipping. 

However, we could not find in the Github post any license associated with the code. Therefore, we would like to ask you for permission to use your code, of course, only for the purpose of research and reproducibility of results. Could you please consider our request.

Please also could you let us know if you have any further questions. 

Best regards,

Dušan Jakovetic, dusan.jakovetic@gmail.com
Dragana Bajovic, dragana.bajovic@gmail.com
Anit Sahu, anit.sahu@gmail.com
Soummya Kar, soummyak@andrew.cmu.edu
Dusan Stamenkovic, dusanstamenkovic95@gmail.com
Nemanja Milosevic, nmilosev@dmi.uns.ac.rs

**Comment by eduardgorbunov** [comment]
Dear colleagues,

Yes, you can post your code under an open-source license and use our code for the purpose of research and reproducibility of results. We do not have any objections. Thank you for your interest in our work :)

Best regards,
Eduard Gorbunov
[eduardgorbunov.github.io](https://eduardgorbunov.github.io/)

**Comment by nmilosev** [comment]
Thank you very much Eduard, we will make sure to let you know when our research is published. :)

Best regards,
Nemanja
